[build]
  command = "JEKYLL_ENV=production NODE_ENV=production jekyll build --trace"
  publish = "_site"
[[headers]]
  for = '*.woff2'
  [headers.values]
    cache-control = 'public, max-age=31536000'